name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Tests & Generate Reports
        run: npm run test

      - name: Upload Jest Test Reports (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: jest-html-report
          path: results/jest/test-report.html
          retention-days: 7
    
      - name: List Jest Report Files (Debugging)
        run: ls -lh results/jest

      - name: Check Jest HTML Report Content
        run: cat results/jest/test-report.html || echo "test-report.html is empty"

      - name: Upload Jest Test Reports (JUnit)
        uses: actions/upload-artifact@v4
        with:
          name: jest-junit-report
          path: results/jest/junit.xml
          retention-days: 7
